### ISSUE TITLE
Bug during ban

### ISSUE THREAD

**Issue by pulse-91** [EinS4ckZwiebeln/IcarusAdvancedAnticheat#68]
**Hello,**

The "Config.BanPlayer" function is not executed. When I spawn a vehicle, it is automatically deleted but the function does not work.
The solution: Restarted the Icarus resource, and now it works. When I restart the resource this is what appears in the console :

![image](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/assets/109738262/e97aa9a9-612b-4b53-af40-b098db2117d2)

A solution to this ? Thanks

**Technical Details:**
 - OS: Linux
 - Artifacts [e.g. 8085]
 - Icarus Version [e.g. 2.0.6b]

**Comment by EinS4ckZwiebeln** [comment]
Hello, sorry to hear that.

1. Does this issue only happen for the EntityCreate module or to other modules as well?

2. Have you started screenshot-basic by any chance? If yes, have you tried this with screenshot-basic stopped?

Attaching your logs from `/Icarus/logs` would also be helpful :)

**Comment by pulse-91** [comment]
I have just done some tests, I am banned when I explode something (grenade), on the other hand for blacklisted weapons, the creation of vehicles and blacklisted objects I am not.

Regarding the error in the screenshot, actually when I stopped screenshot-basic, I no longer had it

Here is the log file as well:
[debug-2024-05-03.log](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/files/15204293/debug-2024-05-03.log)

**Comment by EinS4ckZwiebeln** [comment]
> on the other hand for blacklisted weapons, the creation of vehicles and blacklisted objects I am not

Regarding the blacklisted weapons, that sounds right so far. The player is only banned when he damages a **networked entity** (e.g., a player) with a blacklisted weapon.

On the other hand, you are correct; the spawning of forbidden objects/vehicles should cause the player to be banned. However, I can't reproduce this at all on my system. Just to be sure, have you enabled `banNetworkOwner` for the EntityCreateModule inside the config.lua file?

> Regarding the error in the screenshot, actually when I stopped screenshot-basic, I no longer had it

Yeah, the error is caused by screenshot-basic, not much I can do about that, but not big of a deal also. You can safely ignore this.

**Comment by pulse-91** [comment]
Yes, `banNetworkOwner` is activated. I don't understand, especially when I restart Icarus, it works normally

**Comment by EinS4ckZwiebeln** [comment]
Hmm, strange... I think what you are experiencing could be due to you having admin permissions.

The `useTxAdmin` config option automatically grants all txAdmin administrators bypass permissions for Icarus. And when you restart Icarus, those permissions are reset and not renewed by txAdmin.

You should try disabling `useTxAdmin` in the config. If this doesn't solve the problem, you might have some issues with your resource start order in the server.cfg.

**Comment by pulse-91** [comment]
I deactivated `useTxAdmin`, and changed the order of resources but that doesn't change anything.

**Comment by EinS4ckZwiebeln** [comment]
Would you mind attaching your config.lua file, so I can rule out that this issue is due to a misconfiguration?

**Comment by pulse-91** [comment]
Hi, here is the config.lua file.
[config.txt](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/files/15213129/config.txt)

**Comment by pulse-91** [comment]
Hi, are the configuration files good ?

**Comment by EinS4ckZwiebeln** [comment]
Hi, the config file seems fine to me. However, I still can't reproduce the issue. Have you tried disabling all other resources and/or trying this on a freshly installed server (e.g., localhost)?

**Comment by pulse-91** [comment]
Actually I already tried to deactivate all the resources and there is the same problem.

**Comment by pulse-91** [comment]
It's good I just found the problem, indeed it is indeed linked to txAdmin as you said, but simply that even if we set useTxAdmin to true, the admins are still detected it seems. I logged in with a non-admin account, and it worked.

**Comment by EinS4ckZwiebeln** [comment]
I think I found the issue that was causing this weird behaviour. I uploaded a [new pre-release](https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/releases/tag/release-v2.0.6c) which hopefully should fix the issue you described.

**Comment by pulse-91** [comment]
Perfect, I have just discovered another rather strange behavior, the origin of which I cannot find, when I spawn a non-blacklisted vehicle, then another blacklisted one, both are deleted. I'll provide you with a video so that you understand. Do you know why this happens?

https://github.com/EinS4ckZwiebeln/IcarusAdvancedAnticheat/assets/109738262/9491d8ed-05da-4111-885f-2476833763fb

**Comment by EinS4ckZwiebeln** [comment]
Ah, this feature is intended. This is the config option `cleanUpEntities` which removes all entities spawned by a specific player. This comes in handy when a cheater spawns a lot of different entities that might not all be on the blacklist, so they get removed.

**Comment by pulse-91** [comment]
Okay, thank you for your support, everything is good for me 👍
